// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TemplateApi.Data;

#nullable disable

namespace TemplateApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TemplateApi.Entities.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemId"));

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ItemId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("TemplateApi.Entities.Owner", b =>
                {
                    b.Property<int>("OwnerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OwnerId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("OwnerId");

                    b.ToTable("Owners");
                });

            modelBuilder.Entity("TemplateApi.Entities.Participant", b =>
                {
                    b.Property<int>("ParticipantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ParticipantId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.HasKey("ParticipantId");

                    b.ToTable("Participants");

                    b.HasData(
                        new
                        {
                            ParticipantId = 1,
                            Email = "JOhnDoe@gmail.com",
                            FirstName = "John",
                            LastName = "Doe",
                            Phone = "2345678"
                        },
                        new
                        {
                            ParticipantId = 2,
                            Email = "JOhnDoe@gmail.com",
                            FirstName = "John",
                            LastName = "Doe",
                            Phone = "2345678"
                        },
                        new
                        {
                            ParticipantId = 3,
                            Email = "JOhnDoe@gmail.com",
                            FirstName = "John",
                            LastName = "Doe",
                            Phone = "2345678"
                        });
                });

            modelBuilder.Entity("TemplateApi.Entities.Registration", b =>
                {
                    b.Property<int>("ParticipantId")
                        .HasColumnType("int");

                    b.Property<int>("WorkshopId")
                        .HasColumnType("int");

                    b.Property<int?>("FeedbackId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Registered")
                        .HasColumnType("datetime2");

                    b.HasKey("ParticipantId", "WorkshopId");

                    b.HasIndex("WorkshopId");

                    b.ToTable("Registrations");

                    b.HasData(
                        new
                        {
                            ParticipantId = 1,
                            WorkshopId = 1,
                            FeedbackId = 1,
                            Registered = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ParticipantId = 2,
                            WorkshopId = 1,
                            FeedbackId = 1,
                            Registered = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ParticipantId = 1,
                            WorkshopId = 2,
                            FeedbackId = 1,
                            Registered = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("TemplateApi.Entities.Speaker", b =>
                {
                    b.Property<int>("SpeakerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SpeakerId"));

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SpeakerId");

                    b.ToTable("Speakers");

                    b.HasData(
                        new
                        {
                            SpeakerId = 1,
                            Bio = "goodBio",
                            Email = "JohnPorl@gmail.com",
                            FirstName = "John",
                            LastName = "Pork"
                        },
                        new
                        {
                            SpeakerId = 2,
                            Bio = "goodBio",
                            Email = "JohnPorl@gmail.com",
                            FirstName = "John",
                            LastName = "Pork"
                        },
                        new
                        {
                            SpeakerId = 3,
                            Bio = "goodBio",
                            Email = "JohnPorl@gmail.com",
                            FirstName = "John",
                            LastName = "Pork"
                        });
                });

            modelBuilder.Entity("TemplateApi.Entities.Venue", b =>
                {
                    b.Property<int>("VenueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VenueId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<int>("HasProj")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VenueId");

                    b.ToTable("Venues");

                    b.HasData(
                        new
                        {
                            VenueId = 1,
                            Address = "London",
                            Capacity = 19,
                            HasProj = 1,
                            Name = "London"
                        },
                        new
                        {
                            VenueId = 2,
                            Address = "London",
                            Capacity = 19,
                            HasProj = 1,
                            Name = "London"
                        },
                        new
                        {
                            VenueId = 3,
                            Address = "Shibuya",
                            Capacity = 19,
                            HasProj = 1,
                            Name = "Tokyo"
                        });
                });

            modelBuilder.Entity("TemplateApi.Entities.Workshop", b =>
                {
                    b.Property<int>("WorkShopId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WorkShopId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DifficultyLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("MaxCapacity")
                        .HasColumnType("int");

                    b.Property<int>("SpeakerId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("VenueId")
                        .HasColumnType("int");

                    b.Property<DateTime>("WorkshopDate")
                        .HasColumnType("datetime2");

                    b.HasKey("WorkShopId");

                    b.HasIndex("SpeakerId");

                    b.HasIndex("VenueId");

                    b.ToTable("Workshops");

                    b.HasData(
                        new
                        {
                            WorkShopId = 1,
                            Description = "Writing fast",
                            DifficultyLevel = "Hard",
                            MaxCapacity = 30,
                            SpeakerId = 1,
                            Title = "writing",
                            VenueId = 1,
                            WorkshopDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            WorkShopId = 2,
                            Description = "Writing fast",
                            DifficultyLevel = "Hard",
                            MaxCapacity = 30,
                            SpeakerId = 1,
                            Title = "writing",
                            VenueId = 1,
                            WorkshopDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            WorkShopId = 3,
                            Description = "Writing fast",
                            DifficultyLevel = "Hard",
                            MaxCapacity = 30,
                            SpeakerId = 1,
                            Title = "writing",
                            VenueId = 1,
                            WorkshopDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("TemplateApi.Entities.Item", b =>
                {
                    b.HasOne("TemplateApi.Entities.Owner", "Owner")
                        .WithMany("Items")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("TemplateApi.Entities.Registration", b =>
                {
                    b.HasOne("TemplateApi.Entities.Participant", "Participant")
                        .WithMany()
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TemplateApi.Entities.Workshop", "Workshop")
                        .WithMany()
                        .HasForeignKey("WorkshopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Participant");

                    b.Navigation("Workshop");
                });

            modelBuilder.Entity("TemplateApi.Entities.Workshop", b =>
                {
                    b.HasOne("TemplateApi.Entities.Speaker", "Speaker")
                        .WithMany("Workshops")
                        .HasForeignKey("SpeakerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TemplateApi.Entities.Venue", "Venue")
                        .WithMany("Workshops")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Speaker");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("TemplateApi.Entities.Owner", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("TemplateApi.Entities.Speaker", b =>
                {
                    b.Navigation("Workshops");
                });

            modelBuilder.Entity("TemplateApi.Entities.Venue", b =>
                {
                    b.Navigation("Workshops");
                });
#pragma warning restore 612, 618
        }
    }
}
